server:
  port: 8513
spring:
  application:
    name: service-cart
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
  data:
    redis:
      port: 6379
      host: localhost