# 配置服务端口号
server:
  port: 8501

# 配置数据库连接信息
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_spzx?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: abc123
  # Redis的相关配置
  data:
    redis:
      host: localhost
      port: 6379

# mybatis的配置
mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/*/*.xml

spzx:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
      - /doc.html
      - /webjars/**
      - /v3/api-docs/**
      - /favicon.ico
  minio:
    endpointUrl: http://localhost:9001
    accessKey: admin
    secretKey: admin123456
    bucketName: spzx-bucket